### ISSUE TITLE
Review Week 3

### ISSUE THREAD

**Issue by VinhDevNguyen** [dxv2k/CS112.L12.KHCL#10]
@dxv2k với @Dokkaebi00 Review giúp bài [H_index](https://github.com/dxv2k/CS112.L12.KHCL/blob/Week-3/Week3/H_Index_solution.ipynb). Nếu có vấn đề gì thì comment ở dưới, nếu không có thì comment ở dưới để tiến hành merge branch `Week3` vào branch `master` và sau đó nộp bài lên classroom. Deadline vào tối nay!

**Comment by dxv2k** [comment]
:)) dấu >= sài hình hả. 
Nữa sài này nè $\geq$

**Comment by VinhDevNguyen** [comment]
Thực ra là tao xài $\geq$ nhưng mà cái thằng Github nó render cái đó ra hình á, nên là mày coi bằng Google Colab thì sẽ chuẩn hơn

**Comment by dxv2k** [comment]
ok boiz, ổn đó merge đi. Còn cái bài WaterSupply để tí coi sao, được thì t đạo cmnl =))))

**Comment by VinhDevNguyen** [comment]
Suỵt suỵt, ai đó đọc issue này thì hỏng nhá 😆
