### ISSUE TITLE
Review Computational Thinking

### ISSUE THREAD

**Issue by VinhDevNguyen** [dxv2k/CS112.L12.KHCL#4]
# [Review Computational Thinking](https://github.com/dxv2k/CS112.L12.KHCL/tree/master/Week1/Computational%20Thinking)
If there are any problem, please comment below. If not, tick 'x' on [`1.2. COMPUTATIONAL THINKING`](https://github.com/dxv2k/CS112.L12.KHCL/blob/master/README.md) and close this issue.

**Comment by VinhDevNguyen** [comment]
Review please!!! 😓😓😓

**Comment by dxv2k** [comment]
looks good to me, haven't seen any problem so far!
