### ISSUE TITLE
Review BOT exercise!

### ISSUE THREAD

**Issue by VinhDevNguyen** [dxv2k/CS112.L12.KHCL#5]
# [Review BOT exercise!](https://github.com/dxv2k/CS112.L12.KHCL/blob/BOT_Vu_solution/Week1/BOT/solution.py)
If there are any problem, please comment below. If not, tick 'x' on [1.1. BOT (Built-Operation-Transfer)](https://github.com/dxv2k/CS112.L12.KHCL/blob/master/README.md), close commit and merge branch `BOT_Vu_solution` to `master`

**Comment by VinhDevNguyen** [comment]
https://github.com/dxv2k/CS112.L12.KHCL/blob/ec28de4e35e4c8ebd14d09d6c78050e9f4b27327/Week1/BOT/solution.py#L1-L18
Đoạn code này ông @dxv2k đã tính đến trường hợp **nếu có nhiều cách chọn thì chỉ ra cách chọn có `p` nhỏ nhất** như đề bài đã ghi chưa?

**Comment by VinhDevNguyen** [comment]
Checkout and compare my solution with @dxv2k solution!
## My solution
https://github.com/dxv2k/CS112.L12.KHCL/blob/243f5c7dd448393e328c7fd5e69eed90ced9a95f/Week1/BOT/Vinh_Solution.py#L1-L15

## @dxv2k solution
https://github.com/dxv2k/CS112.L12.KHCL/blob/ec28de4e35e4c8ebd14d09d6c78050e9f4b27327/Week1/BOT/solution.py#L1-L18

**Comment by dxv2k** [comment]
In algorithm design, must use pseudo-code

**Comment by VinhDevNguyen** [comment]
Ok, I will add it into Jupiter notebook version a.s.a.p

**Comment by VinhDevNguyen** [comment]
I created Jupiter Noteboook version, @Dokkaebi00 will take care of the code and I will review it later. If every thing OK. Merge your branch into `master` branch.

**Comment by VinhDevNguyen** [comment]
Please do this a.s.a.p cause deadline is **Due Sep 18**

**Comment by VinhDevNguyen** [comment]
Missing desciption of `Temporary variable`, `Condition` and `Description` of algorithm (Write psudo code in `description`)
@Dokkaebi00 Please add these in [Jupiter Notebook file](https://github.com/dxv2k/CS112.L12.KHCL/blob/BOT_Quang_solution/Week1/BOT/solution.ipynb) a.s.a.p

**Comment by VinhDevNguyen** [comment]
@dxv2k Review [this file](https://github.com/dxv2k/CS112.L12.KHCL/blob/BOT_Quang_solution/Week1/BOT/README.md) and the [JupiterNotebook version](https://github.com/dxv2k/CS112.L12.KHCL/blob/BOT_Quang_solution/Week1/BOT/solution.ipynb) of BOT exercise before we merge `BOT_Quang_solution` branch into `master` branch.

**Comment by VinhDevNguyen** [comment]
Done!
